services:
  app:
    # Busca el dockerfile al mismo nivel
    # El docker file construirá la imagen 
    # poque tambien pondré extensiones
    build: .
    ports: 
    # mi_pc:contenedor
      - '8080:80'
    #Volumen persistente 
    # Enlaza mi pc y el contenedor
    volumes:
      - ./app:/var/www/html/

  db:
    # Averiguar que versión descarga y cambiarla aquí
    image: mysql:9.7.1
    ports:
      - "3306:3306"
    restart: always
    # Variables de entorno
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    # Volumen persistente
    volumes:
      - ./db/mysql-data:/var/lib/mysql