services:
  app:
    
    image: php:8.4-apache
    container_name: php_serve
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    environment:
    # Por si quiero cambiar la ruta raiz
      - APACHE_DOCUMENT_ROOT /var/www/html
    restart: always